### ISSUE TITLE
Wallpaper doesn't change when called by systemd

### ISSUE THREAD

**Issue by frost19k** [hexive/sunpaper#11]
The script runs perfectly when I call it manually, but it doesn't seem to be doing anything when it's called via systemd.

I'm not getting any errors, in fact, systemd reports that it executed without errors. 

> ❯ systemctl status sunpaper_clear_cache.service
> ● sunpaper_clear_cache.service - Clear Sunpaper cache on startup
>      Loaded: loaded (/etc/systemd/system/sunpaper_clear_cache.service; enabled; vendor preset: disabled)
>      Active: active (exited) since Tue 2021-03-30 13:49:22 IST; 11min ago
>     Process: 660 ExecStart=/opt/sunpaper/sunpaper.sh -c (code=exited, status=0/SUCCESS)
>    Main PID: 660 (code=exited, status=0/SUCCESS)
> 
> Mar 30 13:49:22 manjaro-ws sunpaper.sh[660]: cleared wallpaper cache
> Mar 30 13:49:22 manjaro-ws sunpaper.sh[660]: no darkmode day cache found
> Mar 30 13:49:22 manjaro-ws sunpaper.sh[660]: no darkmode night cache found
> Mar 30 13:49:22 manjaro-ws sunpaper.sh[660]: cleared weather cache
> Mar 30 13:49:22 manjaro-ws systemd[1]: Starting Clear Sunpaper cache on startup...
> Mar 30 13:49:22 manjaro-ws systemd[1]: Finished Clear Sunpaper cache on startup.
> 
> ❯ systemctl status sunpaper.timer
> ● sunpaper.timer - Run Sunpaper script to change wallpaper
>      Loaded: loaded (/etc/systemd/system/sunpaper.timer; enabled; vendor preset: disabled)
>      Active: active (waiting) since Tue 2021-03-30 13:49:22 IST; 11min ago
>     Trigger: Tue 2021-03-30 14:02:00 IST; 41s left
>    Triggers: ● sunpaper.service
> 
> Mar 30 13:49:22 manjaro-ws systemd[1]: Started Run Sunpaper script to change wallpaper.
> 
> ❯ systemctl status sunpaper.service
> ● sunpaper.service - Sunpaper wallpaper changer
>      Loaded: loaded (/etc/systemd/system/sunpaper.service; enabled; vendor preset: disabled)
>      Active: inactive (dead) since Tue 2021-03-30 14:01:13 IST; 13s ago
> TriggeredBy: ● sunpaper.timer
>     Process: 3901 ExecStart=/opt/sunpaper/sunpaper.sh (code=exited, status=0/SUCCESS)
>    Main PID: 3901 (code=exited, status=0/SUCCESS)
> 
> Mar 30 14:01:13 manjaro-ws systemd[1]: Started Sunpaper wallpaper changer.
> Mar 30 14:01:13 manjaro-ws systemd[1]: sunpaper.service: Succeeded.

It says it completed successfully but the wallpaper never changes.
I've used the systemd scripts precisely as provided, after updating the PATHs. (I have sunpaper in /opt instead of /home)

The Wiki mentions that I must configure override.conf to my environment - but I'm not entirely sure what I must do.

**Comment by hexive** [comment]
I wish I could be more helpful, but the systemd timer method was passed along from another user and not one that I use personally. And systemd remains a big mystery to me, haha.

Here are some ideas for troubleshooting, though, maybe something here will be useful:

1. If you haven't seen it, here's the original thread where Dave explains his timer setup (maybe he'd be open to questions?):
https://www.reddit.com/r/unixporn/comments/lt7dtq/oc_sunpaper_dynamic_wallpaper_timing_based_on/gp0z79b/

1. I know that setwallpaper uses some environment variables to determine how to best set wallpaper in different WM's ... and I also know those environment variables aren't always available to systemd. To confirm that the issue is with the `setwallpaper` utility you could create a simple bash script with this line and call it from your timer to see if you get a wallpaper change.  
`setwallpaper -m "scale" "/full/path/to/image.jpg"`

1. I believe that when `setwallpaper` cannot determine the best way to set the paper it tries to use `feh` so maybe it's worth a try installing `feh` to your system to see if you get a better result.

1. If you haven't already seen it, here are the github docs for `setwallpaper` utility. They seem pretty good so maybe there is a systemd discussion there in the docs or issues sections that may help point to a solution:
https://github.com/xyproto/wallutils

1. There is someone working on a sunpaper package build for Arch AUR [Issue #10](https://github.com/hexive/sunpaper/issues/10) so if that happens and since you are on manjaro maybe that will be a near-term solution if all else fails.

**Comment by frost19k** [comment]
Thanks for the leads!
I went straight for 2 and it does seem like your suspicions are accurate

```
❯ sudo systemctl status sunpaper.service
● sunpaper.service - Sunpaper wallpaper changer
     Loaded: loaded (/etc/systemd/system/sunpaper.service; disabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/sunpaper.service.d
             └─override.conf
     Active: active (running) since Wed 2021-03-31 16:03:05 IST; 10ms ago
TriggeredBy: ● sunpaper.timer
   Main PID: 6653 (mkwallpaper.sh)
      Tasks: 8 (limit: 38405)
     Memory: 4.1M
     CGroup: /system.slice/sunpaper.service
             ├─6653 /bin/bash /opt/mkwallpaper/mkwallpaper.sh
             ├─6655 setwallpaper -m scale /home/maazb/Pictures/Village/village-1.jpg
             └─6662 feh --bg-scale /home/maazb/Pictures/Village/village-1.jpg

Mar 31 16:03:05 manjaro-ws systemd[1]: Started Sunpaper wallpaper changer.
```
Looks like setwallpaper failed & feh also failed. 

I will reach out to Dave & see if this is something he can help me with.

P.S. I remember seeing sunpaper on the AUR but I think they removed it? Their link leads to a 404.
https://aur.archlinux.org/packages/sunpaper-wallpapers-git/

**Comment by hexive** [comment]
Please let me know if you end up finding a solution. It would be nice to just use systemd to automate this by default to save people from the most complicated configuration step. Thanks for your time on this!

**Comment by hexive** [comment]
Hey @frost19k this is still new and wildly untested but I just pushed a daemon mode that will run the script in the background so you no longer need to automate it with cron / systemd / etc.

Start the daemon with: 
`sunpaper.sh -d`

So you could call that from the list of startup applications in your WM, for example. 

If you ever need to, you can manually stop it with:
`sunpaper.sh -k`

**Comment by frost19k** [comment]
I tested out the daemon mode & it works great! Thanks for that!

I also got it to run with systemd.
I made minor changes to David's unit files & ran them in "user mode".

#Added Unit parameter to Timer section
#Changed WantedBy parameter to default.target
#This will ensure that the timer is activated on reboot
$HOME/.config/systemd/user/sunpaper.timer
```
[Unit]
Description=Run Sunpaper script to change wallpaper

[Timer]
OnCalendar=*:0/1
Unit=sunpaper.service

[Install]
WantedBy=default.target
```

#Make sure that cache is cleared before first run
$HOME/.config/systemd/user/sunpaper.service
```
[Unit]
Description=Sunpaper wallpaper changer
After=sunpaper_cache.service

[Service]
ExecStart=/opt/sunpaper/sunpaper.sh

[Install]
WantedBy=default.target
```

$HOME/.config/systemd/user/sunpaper_cache.service
```
[Unit]
Description=Clear Sunpaper cache on startup

[Service]
Type=oneshot
RemainAfterExit=no
ExecStart=/opt/sunpaper/sunpaper.sh -c

[Install]
WantedBy=default.target
```
#Don't use 'sudo'
systemctl --user daemon-reload
systemctl --user enable --now sunpaper.timer sunpaper_cache.service

I suppose running it in user mode means that it has access to the environment variables - but I can't confirm this. Tried it on a hunch.

Note:
1. I had no need for an "override.conf"
2. Since I've stored it in /opt it'll need 755 permissions to execute in user mode

**Comment by hexive** [comment]
This is great news. I'll update the docs with your configuration.
